# Generated by Django 6.1.1 on 2026-09-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiagnosticCenter',
            new_name='DiagnosticCentre',
        ),
    ]
